// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import MainController from "./main_controller"
application.register("main", MainController)

import AuthController from "./auth_controller"
application.register("auth", AuthController)

