# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-performance

AllCops:
  CacheRootDirectory: tmp/rubocop-cache
  Exclude:
    - db/schema.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Include:
    - app/**/*
    - config/**/*
    - lib/**/*
    - spec/**/*
    - test/**/*
    - Gemfile

Style/ReturnNil:
  Enabled: true
  EnforcedStyle: return

Performance/Count:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/TimesMap:
  Enabled: true
