module Research
  module Modules
    class Base < CandleAligned
      @input_data: Array[research_input_point]
      @time_lookup: Hash[String, Integer]

      def call: (?cancel_check: untyped, ?module_series: research_module_series, **untyped params) -> Array[research_module_point]

      private

      def ta_class: () -> singleton(TechnicalAnalysis::Indicator)
      def result_from: (untyped point) -> research_module_result
      def input_data: () -> Array[research_input_point]
      def time_lookup: () -> Hash[String, Integer]
      def time_for: (String | Time date_time) -> Integer
    end
  end
end
