module Research
  class CancellationCheck
    class Callable
      def initialize: (Proc callable) -> void
      def check_cancelled!: () -> void
    end

    def self.from_proc: (Proc callable) -> Callable
  end
end
